### ISSUE TITLE
Feature: User can Search

### ISSUE THREAD

**Issue by vkalinkin** [vkalinkin/ajax-project#1]
## ⚙️ Feature

User can search for anime/manga series based on a search term.

## 📐 Functionality

Call the API using the API's search term query and then populate the HTML document with matching series.

## 🖼️ Wireframes

![ajax search](https://user-images.githubusercontent.com/33187217/121240180-e7fc2d80-c84e-11eb-9179-b4371b084f98.PNG)

## ✅ Task List

- [x] Create an HTML Skeleton with the necessary elements.
- [x] Create JS code that can populate the HTML list from a hardcoded search-term variable
- [x] Create a search bar that can take the text from a search bar and assign it to a variable when the search button is pressed.
- [x] Make sure the HTML list is getting populated from the search term from the search button
- [x] Add radio buttons for anime and manga
- [x] Make sure the search function can handle searches based on the anime/manga radio buttons
- [x] Check to see if everything is working correctly
- [x] Add CSS to polish up the look.
