### ISSUE TITLE
Convert to ES6

### ISSUE THREAD

**Issue by vkalinkin** [vkalinkin/ajax-project#13]
## 📐 Functionality

Convert Javascript code from ES5 to ES6.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Convert vars that don't change to const
- [x] Convert vars that do change to let
- [x] Make sure functionality is the same as before
