### ISSUE TITLE
Feature: User can get Recent Anime

### ISSUE THREAD

**Issue by vkalinkin** [vkalinkin/ajax-project#2]
## ⚙️ Feature

User can click on 'get anime from the most recent season' button to get all the shows airing in the latest season.

## 📐 Functionality

Call the API to get all series from Spring 2021 season and populated the HTML

## 🖼️ Wireframes

![ajax current season](https://user-images.githubusercontent.com/33187217/121241683-8e94fe00-c850-11eb-99e9-2e68ce9f252c.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add new HTML for a new view for season search
- [x] Add JS and CSS so user can swap between the 2 views
- [x] Add JS code that populates the list with shows from the Spring 2021 season
- [x] Check that code is working correctly
- [x] Add CSS styling to polish up the look
