### ISSUE TITLE
Feature: User can see Previous Seasons

### ISSUE THREAD

**Issue by vkalinkin** [vkalinkin/ajax-project#3]
## ⚙️ Feature

User can pick specific previous season to see all the shows that aired during those past seasons.

## 📐 Functionality

Based on the season the user picks from the drop down list, the HTML document gets populated with those series

## 🖼️ Wireframes

![ajax past seasons](https://user-images.githubusercontent.com/33187217/121241988-e3d10f80-c850-11eb-8b53-07cc963c3413.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add radio buttons for current and past seasons
- [x] Edit HTML to add 2 drop down lists, one for year and one for season
- [x] Write JS/CSS to make drop downs visible only if past seasons radio button is checked
- [x] Write JS code so that the value of the season variable can be changed to whatever season is selected from the drop downs
- [x] Populate the list with shows based on the season from the drop downs
- [x] Make sure code is working
- [x] Add CSS stylings
