### ISSUE TITLE
Feature: User can get more Info

### ISSUE THREAD

**Issue by vkalinkin** [vkalinkin/ajax-project#4]
## ⚙️ Feature

User can press More Info button to see series data

## 📐 Functionality

When User clicks on More Info button, a modal appears that has additional information on the series. This includes information from a different API call (calling the API with the exact anime id instead of just calling the API with a search term)

## 🖼️ Wireframes

![ajax get more info](https://user-images.githubusercontent.com/33187217/121242449-6e197380-c851-11eb-9549-13bfcdb44139.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Modify the JS that creates divs for show entries so each show entry has a More Info button
- [x] Create HTML/CSS for a More Info modal
- [x] Have the modal appear when the More Info button is pressed
- [x] Write JS code that calls the API with the mal_id of the associated show that get it's More Info button clicked and gets extra info about the show.
- [x] Populated the modal with that info
- [x] Have the modal close when the user clicks Ok button
- [x] Check if code is working properly/any additional CSS stylings
