### ISSUE TITLE
Feature: User can Save Favorites

### ISSUE THREAD

**Issue by vkalinkin** [vkalinkin/ajax-project#5]
## ⚙️ Feature

User can press on a Star icon next to the series in the search results list to add the series to their list. They can also open the list to see the series that they starred.

## 📐 Functionality

When the user clicks on the Star the series gets saved to a favorites array. When the user clicks on 'See List', the contents of the Favorites array populated the page.

## 🖼️ Wireframes

![ajax fave](https://user-images.githubusercontent.com/33187217/121246298-e08c5280-c855-11eb-84c3-c6d1ca415c4b.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML/CSS for a My List & Search button
- [x] Modify the JS to create a star icon for each series listing
- [x] Give the Star icon attributes of series name, year, image url, etc.
- [x] When the user clicks on a star, save it's attributes to local data storage and change the star's color
- [x] When user clicks on My List, load up the results list with shows stored in local storage
- [x] When user clicks on Search, return to search view
- [x] If entry is already in favorites, it's star should already be in a difference color
- [x] Test for bugs and CSS styling
